#!/bin/bash
# Argument sanity checking eliminated for brevity

readonly command_log="${HOME}/bin/qiv-command.log"

readonly command_number=$1
readonly image=$2

print_usage(){
    echo "$0 [-a artist -w web -t title -d date] picture"
    exit 1
}

if [ "$#" -gt 0 ]; then
    while getopts "a:w:t:d:" options; do
	case "${options}" in
            a)
                readonly artist="-M"\""set Exif.Image.Artist ${OPTARG}"\"
		;;
	    w)
		readonly web="-M"\""set Xmp.xmpRights.WebStatement ${OPTARG}"\"
		;;
            t)
                readonly title="-M"\""set Xmp.dc.title ${OPTARG}"\"
                ;;
            d)
                readonly date="-M"\""set Xmp.dc.date ${OPTARG}"\"
                ;;
            *)
		echo "Unknow option" 1>&2 
		print_usage
		;;

	esac
    done
    shift $((OPTIND-1))
fi

picture=$1
[ -z "${picture}" ] && print_usage

eval exiv2 ${artist} ${web} ${title} ${date} ${picture}
exiv2 -M"set Xmp.xmpRights.Marked True" -M"set Xmp.xmpRights.UsageTerms This work is licensed to the public under the Creative Commons Attribution-NonCommercial license https://creativecommons.org/licenses/by-nc/2.0/" ${picture}

# comprobar los campos de los metadatos
exiv2 -pa ${picture}
