#!/bin/bash
# Argument sanity checking eliminated for brevity

readonly command_log="${HOME}/bin/qiv-command.log"

readonly command_number=$1
readonly image=$2

log_command(){
	echo "$1" >> ${command_log}
}

case ${command_number} in
    1)
        # Set image comment
	readonly comment=$(zenity  --title "Comment" --entry --text "Picture comment:")
	exiftool -comment="${comment}" "${image}" 
	log_command "exiftool -comment='${comment}' '${image}'" 
    ;;
    2)  
        # Crop image
        mirage "${image}" & 
        ;;
    4) 
        # Add tags to image
	tag=$(zenity --height 400 --list  --column "Tag" capoeira happy-japan)
	exiftool -keyword+=${tag} "${image}"  
	log_command "exiftool -keyword+=${tag} '${image}'"
    ;;
    5) 
        # (un)Star image
        operation="+"
        exiftool -a "${image}" | grep star && operation="-"
	exiftool -keyword${operation}=star "${image}"  
	log_command "exiftool -keyword${operation}=star '${image}'"
    ;;
    6) 
        # Get tags and comment
	exiftool -a "${image}" | egrep "Comment|Keyword"
    ;;
    7)
	# mark for deletion - not needed, qiv provides "d" command
	# echo "${image}" >> images_to_delete
	# Rotate
	mogrify -rotate "-90" "$2"; exit;;
    ;;
    8) mogrify -rotate "90" "$2"; exit;;
	;;
    *) 
        echo "Unrecognized command";
        exit 2
    ;;
esac

