#!/bin/bash
# Monitor MOAB's idle processors
# Author: Jesus Cuenca (jesus.cuenca@gmail.com)
# See License file

. /etc/nagios/custom_scripts.cfg
. ${MOAB_LIB}

parse_cmd_arguments $@

readonly idle=$( get_idle_processors )

check_value ${idle} ${WARNING} ${CRITICAL}
status=$?
echo ${idle}
exit ${status}

