#!/bin/bash
# Monitor MOAB's idle nodes
# Author: Jesus Cuenca (jesus.cuenca@gmail.com)
# See License file

. /etc/nagios/custom_scripts.cfg
. ${MOAB_LIB}

parse_cmd_arguments $@

# Number of idle nodes
readonly idle_nodes=$( get_idle_nodes )

check_value ${idle_nodes} ${WARNING} ${CRITICAL}
status=$?
echo ${idle_nodes}
exit ${status}

