#!/bin/bash
# Monitor MOAB's active jobs
# Author: Jesus Cuenca (jesus.cuenca@gmail.com)
# See License file

. /etc/nagios/custom_scripts.cfg
. ${MOAB_LIB}

parse_cmd_arguments $@

active=$( get_active_jobs )
readonly cmd_return=$?
if [ "a${active}" == "a" ]; then
    active="?"
fi
check_value "${active}" ${WARNING} ${CRITICAL} ${cmd_return}
status=$?
echo ${active}
exit ${status}

