#!/bin/bash
# Monitor green nodes
# Author: Jesus Cuenca (jesus.cuenca@gmail.com)
# See License file

. $(dirname ${BASH_SOURCE[0]})/nagios_common.sh
. ${MOAB_LIB}

parse_cmd_arguments $@

readonly license_status=$( get_license_status )

check_text_value ${license_status} "expired."
status=$?
exit ${status}
