#!/bin/bash
# Monitor MOAB's idle processors
# Author: Jesus Cuenca (jesus.cuenca@gmail.com)
# See License file

. $(dirname ${BASH_SOURCE[0]})/nagios_common.sh
. ${MOAB_LIB}

parse_cmd_arguments $@

readonly idle=$( get_idle_processors )

check_value ${idle} ${WARNING} ${CRITICAL}
status=$?
echo ${idle}
exit ${status}

