#!/bin/bash
# Monitor MOAB's active jobs
# Author: Jesus Cuenca (jcuenca@cnb.csic.es)
# See License file

. /etc/nagios/custom_scripts.cfg
. ${MOAB_LIB}

parse_cmd_arguments $@

readonly active=$( get_active_jobs )

check_value ${active} ${WARNING} ${CRITICAL}
status=$?
echo ${active}
exit ${status}

