#!/bin/bash
# Monitor MOAB's down nodes
# Author: Jesus Cuenca (jcuenca@cnb.csic.es)
# See License file

. /etc/nagios/custom_scripts.cfg
. ${MOAB_LIB}

parse_cmd_arguments $@

readonly down_nodes=$( get_down_nodes )
readonly green_nodes=$( get_green_nodes )
readonly result=$(( down_nodes - green_nodes ))

check_value ${result} ${WARNING} ${CRITICAL}
status=$?
echo ${result}
exit ${status}