#!/bin/bash
# Monitor MOAB's blocked jobs
# Author: Jesus Cuenca (jcuenca@cnb.csic.es)
# See License file

. /etc/nagios/custom_scripts.cfg
. ${MOAB_LIB}

parse_cmd_arguments $@

blocked=$( get_blocked_jobs )
readonly cmd_return=$?
if [ "a${blocked}" == "a" ]; then
    blocked="?"
fi
check_value "${blocked}" ${WARNING} ${CRITICAL} ${cmd_return}

status=$?
echo ${blocked}
exit ${status}

