#!/bin/bash
# Monitor MOAB's blocked jobs
# Author: Jesus Cuenca (jesus.cuenca@gmail.com)
# See License file

. $(dirname ${BASH_SOURCE[0]})/nagios_common.sh
. ${MOAB_LIB}

parse_cmd_arguments $@

blocked=$( get_blocked_jobs )
readonly cmd_return=$?
if [ "a${blocked}" == "a" ]; then
    blocked="?"
fi
check_value "${blocked}" ${WARNING} ${CRITICAL} ${cmd_return}

status=$?
echo ${blocked}
exit ${status}

