#!/bin/bash

# Helper script for web content monigoring
# Author: Jesus Cuenca (jcuenca@cnb.csic.es)
# See License file

. /etc/nagios/custom_scripts.cfg

HEX_OPTIONS="cat - "

parse_cmd_arguments "$@"

readonly start_time=$(date +%s)
wget --quiet -O - ${URL} | ${HEX_OPTIONS} | grep "$KEYPHRASE" > /dev/null
readonly found=$?

readonly end_time=$(date +%s)
readonly time_diff=$(( end_time - start_time))


if [ ${found} -ne 0 ]; then
	status=2
	echo -n "[CRITICAL] WEBCONTENT=$status $KEYPHRASE not found in page "
elif [ ${time_diff} -gt 3 ];then
	status=1
	echo -n "[WARNING] WEBCONTENT slow (${time_diff} seconds) "
elif [ ${time_diff} -gt 6 ];then
	status=2
	echo -n "[CRITICAL] WEBCONTENT slow (${time_diff} seconds) "
else
	status=0
	echo -n "[OK] WEBCONTENT OK, pageload ${time_diff} seconds"
fi
exit $status
