#!/bin/bash
# Monitor green nodes
# Author: Jesus Cuenca (jesus.cuenca@gmail.com)
# See License file

. /etc/nagios/custom_scripts.cfg
. ${MOAB_LIB}

parse_cmd_arguments $@

readonly green_nodes=$( get_green_nodes )

check_value ${green_nodes} ${WARNING} ${CRITICAL}
status=$?
echo ${green_nodes}
exit ${status}
